import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";

export interface GridPdfOptions {
  filename: string;
  poolName: string;
  sport: string;
  subtitle: string;
  columns: string[];
  rows: { cells: string[]; isCurrentUser?: boolean }[];
  footer: string;
}

export function downloadGridPdf({
  filename,
  poolName,
  sport,
  subtitle,
  columns,
  rows,
  footer,
}: GridPdfOptions): void {
  const doc = new jsPDF({ orientation: "landscape", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  let y = 16;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 80, 200);
  doc.text("SURVIVOR SHARKS", margin, y);
  y += 9;

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 20, 40);
  doc.text(poolName.toUpperCase(), margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 120);
  doc.text(`${sport}  ·  ${subtitle}`, margin, y);
  y += 5;

  doc.setDrawColor(200, 205, 220);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageW - margin, y);
  y += 4;

  const lastColKey = String(columns.length - 1);

  autoTable(doc, {
    startY: y,
    head: [columns],
    body: rows.map((r) => r.cells),
    margin: { left: margin, right: margin, bottom: 16 },
    styles: {
      fontSize: 7.5,
      cellPadding: 3,
      halign: "center",
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: [15, 23, 42] as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold",
      halign: "center",
    },
    bodyStyles: {
      textColor: [30, 30, 50] as [number, number, number],
    },
    alternateRowStyles: {
      fillColor: [246, 247, 252] as [number, number, number],
    },
    columnStyles: {
      "0": { halign: "left", fontStyle: "bold", cellWidth: 40 },
      [lastColKey]: { halign: "right", fontStyle: "bold" },
    },
  });

  const totalPages = doc.getNumberOfPages();
  const now = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 170);
    doc.text("Generated by Survivor Sharks", margin, pageH - 8);
    doc.text(`Page ${i} of ${totalPages}`, pageW / 2, pageH - 8, { align: "center" });
    doc.text(now, pageW - margin, pageH - 8, { align: "right" });
    doc.setFontSize(7);
    doc.text(footer, pageW / 2, pageH - 4, { align: "center" });
  }

  doc.save(filename);
}
